# Copyright (c) 2025 Salvo Giangreco
# SPDX-License-Identifier: GPL-3.0-or-later

# SEC Floating Feature configuration file for Qualcomm Snapdragon 730G devices (sm7150)

# Display
SEC_FLOATING_FEATURE_COMMON_CONFIG_MDNIE_MODE=62481

# High Performance Mode
SEC_FLOATING_FEATURE_COMMON_SUPPORT_HIGH_PERFORMANCE_MODE=TRUE
SEC_FLOATING_FEATURE_SYSTEM_SUPPORT_ENHANCED_CPU_RESPONSIVENESS=TRUE

# Enable Video brightness feature
SEC_FLOATING_FEATURE_COMMON_SUPPORT_HDR_EFFECT=true

# Enable Extra Brightness feature
SEC_FLOATING_FEATURE_LCD_SUPPORT_EXTRA_BRIGHTNESS=TRUE

# Upgrade ImageTagger version
SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_VERSION=V701

# Saiv
SEC_FLOATING_FEATURE_SAIV_CONFIG_ARDOODLE_LIB=PET_DETECTION,IMG_PICKING
SEC_FLOATING_FEATURE_SAIV_CONFIG_AI_REVITAL_VERSION=1.7,1
SEC_FLOATING_FEATURE_GENAI_SUPPORT_TIME_WEATHER_WALLPAPER=V2
SEC_FLOATING_FEATURE_SAIV_CONFIG_MIDAS=UPSCALE,UPSCALE_PRO,UPSCALE_ULTRA,LOWLIGHT,HDR,DEBLUR,MOIRE,DENOISE,SHADOW,REFLECTION,UWDC,FLARE,FACERESTORATION

# Lockscreen
SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_WALLPAPER_STYLE=VIDEO,GENWEATHER